### ISSUE TITLE
v13 Proto issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/FreeSoc2#5]
Just two:

(1) Got some weird net action going on on the input side of the vregs (SCH page(2)), it looks like the vreg symbols got moved around a bit.

(2) The two new resistors off of the vregs need the PROD_ID in the attributes. As far as I'm concerned, as long as this is fixed before REDs I'm cool with it staying as is through the protos if we want to get these out ASAP.

that's it!

**Comment by mhord** [comment]
Fixed and pushed.
